name: Build and Test

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]
  workflow_dispatch:

env:
  DOTNET_VERSION: "8.0.x"
  AZURE_FUNCTIONAPP_PACKAGE_PATH: "AzureFunction"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    outputs:
      infra-changed: ${{ steps.changes.outputs.infra }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Detect changes
        uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            infra:
              - 'infra/**'
            app:
              - 'AzureFunction/**'
              - 'AzureFunction.Tests/**'

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Cache NuGet packages
        uses: actions/cache@v4
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Restore dependencies
        run: dotnet restore

      - name: Lint Bicep files
        if: steps.changes.outputs.infra == 'true'
        uses: azure/cli@v2
        with:
          inlineScript: |
            az bicep lint --file infra/main.bicep

      - name: Build solution
        run: dotnet build --configuration Release --no-restore

      - name: Run tests
        run: dotnet test --configuration Release --no-build --verbosity normal --collect:"XPlat Code Coverage"

      - name: Publish Function App
        run: |
          dotnet publish ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }} \
            --configuration Release \
            --output ./publish \
            --no-build

      - name: Create deployment package
        run: |
          cd publish
          zip -r ../function-app.zip *
          cd ..

      - name: Upload Function App as release asset
        if: github.ref == 'refs/heads/main'
        uses: actions/upload-artifact@v4
        with:
          name: function-app-build-${{ github.sha }}
          path: function-app.zip
          retention-days: 30

      - name: Upload Bicep as release asset
        if: github.ref == 'refs/heads/main' && steps.changes.outputs.infra == 'true'
        uses: actions/upload-artifact@v4
        with:
          name: bicep-templates-build-${{ github.sha }}
          path: infra/
          retention-days: 30

      - name: Setup Node.js (for semantic versioning)
        if: github.ref == 'refs/heads/main'
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Run semantic-release (main branch only)
        if: github.ref == 'refs/heads/main'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Update package.json with correct repository URL
          npm pkg set repository.url="https://github.com/${{ github.repository }}.git"
          npx semantic-release
